config/routes.rb
Rails.application.routes.draw do
  get 'messages/websockets' => 'messages#new_websockets'
  get 'messages/shortpoll' => 'messages#new_shortpoll'
  get 'messages/streaming' => 'messages#new_streaming'
  get 'messages/actioncable' => 'messages#new_actioncable'

  get 'home' => 'home#index'

  get 'sessions/new'

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  resources :users
  resources :sessions
  resources :messages do
    collection do
      get :events
    end
  end

  resources :home

  root :to => "home#index"
end

app/models/message.rb
class Message < ActiveRecord::Base

  attr_accessor :username

  validates_presence_of :text
  validates_presence_of :user

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password

  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :name
  validates_uniqueness_of :name

  has_many :messages

  def self.authenticate(name, password)
    user = find_by_name(name)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def default_serializer_options
    { root: false }
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def check_session
    if current_user == nil
      redirect_to new_session_path, :notice => 'You need to log in to start chatting'
    else
    end
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :check_session

  def index
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include ActionController::Live

  before_filter :check_session, except: :events

  def index
    @messages = Message.where("created_at > ?", 3.seconds.ago)
    render json: @messages
  end

  def new_websockets
      @message = Message.new
  end

  def new_actioncable
      @message = Message.new
  end

  def new_shortpoll
      @message = Message.new
  end

  def new_streaming
      @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @message.user = current_user
    if @message.save
      WebsocketRails[:messages].trigger('new', message)
      ActionCable.server.broadcast 'message',
        text: @message.text,
        user: @message.user.name,
        time: @message.created_at.strftime('%H:%M:%S')
      render json: { success: true }
    end
  end

  def events
    response.headers["Content-Type"] = "text/event-stream"
    start = Time.now
    10.times do
      Message.uncached do
        Message.where('created_at > ?', start).each do |msg|
          msg.username = msg.user.name
          msg.save
          response.stream.write "data: #{msg.to_json(:methods => :username)}\n\n"
          start = message.created_at
        end
      end
      sleep 3
    end
  rescue IOError
    logger.info "Stream closed"
  ensure
    response.stream.close
  end

  def message
    {
      text: @message.text,
      user: @message.user.name,
      time: @message.created_at.strftime('%H:%M:%S')
    }
  end

  def message_params
    params.require(:message).permit(:text)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.authenticate(params[:name], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to home_index_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid name or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path, :notice => "Signed up!"
    else
      render "new"
    end
  end

  def user_params
    params.require(:user).permit(:name, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.haml
%h1 Home
%h3 please select chat:
= link_to "Websockets", "messages/websockets"
%br
= link_to "Actioncable", "messages/actioncable"
%br
= link_to "Shortpoll", "messages/shortpoll"
%br
= link_to "Streaming", "messages/streaming"

app/views/layouts/application.haml
!!!
%html
  %head
    %title RealtimeChat
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false
    = javascript_include_tag 'application', 'data-turbolinks-track' => false
    = csrf_meta_tags
  %body
    .container
      %nav.navbar.navbar-default
        .navbar-header
          %span.navbar-brand
            = link_to "Chat", home_path
            |
            - if current_user
              Logged in as #{current_user.name}.
              \#{link_to "Log out", log_out_path}
            - else
              = link_to "Sign up", sign_up_path
              or
              \#{link_to "log in", log_in_path}
          - flash.each do |name, msg|
            = content_tag :div, msg, :id => "flash_#{name}"
      = yield

app/views/messages/new.html.haml
.main
  .row
    %p
      .col-md-4.chat{id: "user"}
        .messages.well
        %form.form-inline
          .form-group
            %input.form-control{:placeholder => "Lets chat!" }
          %button.btn.btn-success
            submit

app/views/messages/new_actioncable.haml
.main
  %h3
    Actioncable
  .row
    %p
      .col-md-4.chat{id: "user"}
        .messages-actioncable.well
        %form.form-inline
          .form-group
            %input.form-control{:placeholder => "Lets chat!" }
          %button.btn.btn-success
            submit

app/views/messages/new_shortpoll.haml
= javascript_include_tag 'shortpoll'
.main
  %h3
    Shortpoll
  .row
    %p
      .col-md-4.chat{id: "user"}
        .messages-shortpoll.well
        %form.form-inline
          .form-group
            %input.form-control{:placeholder => "Lets chat!" }
          %button.btn.btn-success
            submit

app/views/messages/new_streaming.haml
= javascript_include_tag 'streaming'
.main
  %h3
    Streaming
  .row
    %p
      .col-md-4.chat{id: "user"}
        .messages-streaming.well
        %form.form-inline
          .form-group
            %input.form-control{:placeholder => "Lets chat!" }
          %button.btn.btn-success
            submit

app/views/messages/new_websockets.haml
= javascript_include_tag 'websockets'
.main
  %h3
    Websockets
  .row
    %p
      .col-md-4.chat{id: "user"}
        .messages-websockets.well
        %form.form-inline
          .form-group
            %input.form-control{:placeholder => "Lets chat!" }
          %button.btn.btn-success
            submit

app/views/users/new.haml
%h1 Sign Up
= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @user.errors.full_messages
          %li= message
  %p
    = f.label :name
    %br/
    = f.text_field :name
  %p
    = f.label :password
    %br/
    = f.password_field :password
  %p
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  %p.button= f.submit